# Generated by Django 4.2.3 on 2023-08-02 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contacto_asunto_contacto_tipo_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='asunto',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='tipo_consulta',
            field=models.CharField(choices=[('pregunta_general', 'Pregunta general'), ('sugerencia', 'Sugerencia'), ('reportar_problema', 'Reportar un problema')], max_length=50),
        ),
    ]
