# Generated by Django 4.2.3 on 2023-07-27 00:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
