# Generated by Django 4.2.3 on 2023-07-27 02:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0004_comment_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='meGusta',
            field=models.ManyToManyField(blank=True, related_name='publicaciones_gustadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
